name: dam_project
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  sqflite: ^2.4.2
  path: ^1.9.1
  crypto: ^3.0.6
  http: ^1.3.0
  iconsax: ^0.0.8
  flutter_rating_bar: ^4.0.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/login/
    - assets/images/onboarding/
    - assets/images/recipes/
